remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: "AutoSSH Tool"
description: "Connection for a rapid SSH connection"
baseurl: "/AutoSSH-Tools"
url: "https://veronne2010.github.io"
