remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: "AutoSSH Tools"
description: "Autogen of SSH connection command"
baseurl: "/AutoSSH-Tools"
url: "https://age13programmer.github.io"
